import { useRouter } from 'next/router'
import { useState, useEffect } from 'react'
import Layout from '../../components/Layout'
import Link from 'next/link'

// Mock data - in a real app this would come from a database
const artworks = {
  '1': {
    id: '1',
    title: 'QUANTUM ENTANGLEMENT',
    year: '2023',
    medium: 'Digital painting on blockchain',
    image: 'https://placehold.co/800x600',
    dimensions: '4000 × 4000 px',
    description: 'This piece explores the concept of quantum entanglement through algorithmic art generation. The interconnected patterns represent the non-local correlations that exist in quantum systems, challenging our classical understanding of space and time.',
    price: '2.5 ETH',
    available: true
  },
  '2': {
    id: '2',
    title: 'NEURAL LANDSCAPE',
    year: '2022',
    medium: 'AI-assisted acrylic',
    image: 'https://placehold.co/800x600',
    dimensions: '120 × 80 cm',
    description: 'A hybrid work combining traditional acrylic painting with AI-generated elements. The neural network patterns emerge from the organic brushstrokes, creating a dialogue between human creativity and artificial intelligence.',
    price: '€8,500',
    available: true
  },
  '3': {
    id: '3',
    title: 'DIGITAL CONSCIOUSNESS',
    year: '2023',
    medium: 'Algorithmic art',
    image: 'https://placehold.co/800x600',
    dimensions: '3000 × 2000 px',
    description: 'An exploration of digital consciousness through generative algorithms. The piece questions what it means to be aware in a digital realm, blurring the lines between artificial and human intelligence.',
    price: '1.8 ETH',
    available: true
  },
  '4': {
    id: '4',
    title: 'METAVERSE FRAGMENTS',
    year: '2022',
    medium: 'Mixed media digital',
    image: 'https://placehold.co/800x600',
    dimensions: '150 × 100 cm',
    description: 'Fragments of virtual worlds captured and reimagined. This work examines the transient nature of digital spaces and our relationship with virtual reality as an extension of human experience.',
    price: '€6,200',
    available: false
  },
  '5': {
    id: '5',
    title: 'SYNTHETIC REALITY',
    year: '2023',
    medium: 'Generative art',
    image: 'https://placehold.co/800x600',
    dimensions: '5000 × 3000 px',
    description: 'A meditation on the synthetic nature of our digital existence. The generative patterns create a reality that is both artificial and beautiful, questioning our perception of what is real.',
    price: '3.2 ETH',
    available: true
  },
  '6': {
    id: '6',
    title: 'ALGORITHMIC DREAMS',
    year: '2021',
    medium: 'Digital painting',
    image: 'https://placehold.co/800x600',
    dimensions: '2000 × 2000 px',
    description: 'Dreams generated by algorithms, exploring the subconscious mind of artificial intelligence. This piece bridges the gap between human imagination and machine learning creativity.',
    price: '€4,800',
    available: true
  }
}

export default function ArtworkDetail() {
  const router = useRouter()
  const [artwork, setArtwork] = useState<any>(null)
  const [loading, setLoading] = useState(true)
  const [notFound, setNotFound] = useState(false)

  useEffect(() => {
    if (router.isReady) {
      const { id } = router.query
      const artworkId = Array.isArray(id) ? id[0] : id
      
      if (artworkId && artworks[artworkId as keyof typeof artworks]) {
        setArtwork(artworks[artworkId as keyof typeof artworks])
        setNotFound(false)
      } else {
        setNotFound(true)
      }
      setLoading(false)
    }
  }, [router.isReady, router.query])

  if (loading) {
    return (
      <Layout title="Loading... | Marc Le">
        <div className="max-w-4xl mx-auto px-4 py-8">
          <div className="text-center">
            <h1 className="text-4xl font-bold text-[var(--color-text-main)] mb-4">Loading...</h1>
            <p className="text-[var(--color-text-secondary)]">Please wait while we load the artwork.</p>
          </div>
        </div>
      </Layout>
    )
  }

  if (notFound || !artwork) {
    return (
      <Layout title="Artwork Not Found | Marc Le">
        <div className="max-w-4xl mx-auto px-4 py-8">
          <div className="text-center">
            <h1 className="text-4xl font-bold text-[var(--color-text-main)] mb-4">Artwork Not Found</h1>
            <p className="text-[var(--color-text-secondary)] mb-8">The artwork you're looking for doesn't exist.</p>
            <Link href="/paintings" className="text-[var(--color-accent-blue)] hover:underline font-medium">
              ← Back to Paintings
            </Link>
          </div>
        </div>
      </Layout>
    )
  }

  return (
    <Layout title={`${artwork.title} | Marc Le`}>
      <div className="max-w-4xl mx-auto px-4 py-8">
        <div className="mb-8">
          <Link href="/paintings" className="text-[var(--color-accent-blue)] hover:underline font-medium">
            ← Back to Paintings
          </Link>
        </div>

        <div className="grid md:grid-cols-2 gap-8">
          <div>
            <img 
              src={artwork.image} 
              alt={artwork.title} 
              className="w-full h-[400px] object-cover rounded-lg shadow-sm"
            />
          </div>
          
          <div className="space-y-6">
            <div>
              <h1 className="text-3xl font-bold text-[var(--color-text-main)] mb-2">{artwork.title}</h1>
              <p className="text-[var(--color-text-secondary)]">{artwork.year}</p>
            </div>
            
            <div className="space-y-3">
              <div>
                <span className="font-medium text-[var(--color-text-main)]">Medium:</span>
                <span className="text-[var(--color-text-secondary)] ml-2">{artwork.medium}</span>
              </div>
              <div>
                <span className="font-medium text-[var(--color-text-main)]">Dimensions:</span>
                <span className="text-[var(--color-text-secondary)] ml-2">{artwork.dimensions}</span>
              </div>
              <div>
                <span className="font-medium text-[var(--color-text-main)]">Price:</span>
                <span className="text-[var(--color-accent-blue)] ml-2 font-bold">{artwork.price}</span>
              </div>
              <div>
                <span className="font-medium text-[var(--color-text-main)]">Status:</span>
                <span className={`ml-2 ${artwork.available ? 'text-green-600' : 'text-red-600'}`}>
                  {artwork.available ? 'Available' : 'Sold'}
                </span>
              </div>
            </div>
            
            <div>
              <h2 className="text-xl font-bold text-[var(--color-text-main)] mb-3">Description</h2>
              <p className="text-[var(--color-text-main)] leading-relaxed">{artwork.description}</p>
            </div>
            
            {artwork.available && (
              <div className="pt-4">
                <Link 
                  href="/shop" 
                  className="inline-block bg-[var(--color-accent-blue)] text-white px-6 py-3 rounded-lg font-medium hover:bg-[var(--color-accent-blue)]/90 transition-colors"
                >
                  Purchase Artwork
                </Link>
              </div>
            )}
          </div>
        </div>
      </div>
    </Layout>
  )
} 